name: RisenBoss
description: A supporting plugin for the FallenMC minecraft server that adds the risen boss.
version: 1.0
author: FallenMC team
main: xyz.fallenmc.risenboss.main.RisenMain
depend:
  - Fallen

commands:
  rise:
    description: Command mainly used to activate the risen boss for a certain player. Can only be used by server admins.
    usage: /<command> <player>
  endboss:
    description: Ends the current Risen Boss with the reason as an unknown win or loss. Can only be used by server admins.
    usage: /<command> <win|loss>